export const restaurantData = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "359046",
        name: "Kailash Parbat",
        uuid: "641a7305-0fe8-48fe-9aa5-153bf5e694cf",
        city: "1",
        area: "Sadashiv Nagar",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "fer25owpwwa9soic6a1y",
        cuisines: ["Fast Food", "North Indian", "Street Food"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 3.9000000953674316,
        slugs: {
          restaurant: "kailash-parbat-sadashivnagar-malleshwaram",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "No 381 13th Cross street Sadashiv Nagar   (Next to Punjab National Bank) Bangalore 560080",
        locality: "Armane Nagar",
        parentId: 1933,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3300,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=6894507~p=25~eid=00000188-fcab-e1c5-15fb-f4aa00221948~srvts=1687866302917",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "359046",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 3.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "3368",
        name: "Truffles",
        uuid: "6cb747e4-bf98-442c-a3c6-004ef92587b8",
        city: "1",
        area: "New BEL Road",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "cd832b6167eb9f88aeb1ccdebf38d942",
        cuisines: ["American", "Desserts", "Italian", "Continental"],
        tags: [],
        costForTwo: 45000,
        costForTwoString: "₹450 FOR TWO",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: "33 MINS",
        lastMileTravel: 1.399999976158142,
        slugs: {
          restaurant:
            "truffles-ice-spice-sanjay-nagar-new-bel-road-yeshwanthpur",
          city: "bangalore",
        },
        cityState: "1",
        address: "84, 80 Feet Road, RMV 2nd Stage, New BEL Road, Bangalore",
        locality: "Ms Ramaiah Nagar",
        parentId: 218065,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "3368",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 1.399999976158142,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.4",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "473374",
        name: "Sandos 'n Grills - Gourmet Burgers",
        uuid: "153bd714-45d8-4f1d-9e09-f09afff23864",
        city: "1",
        area: "Sanjay Nagar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "uszqail6u8uggn5gmpgv",
        cuisines: [
          "American",
          "Continental",
          "Italian",
          "Pastas",
          "Beverages",
          "Desserts",
        ],
        tags: [],
        costForTwo: 45000,
        costForTwoString: "₹450 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 2.9000000953674316,
        slugs: {
          restaurant:
            "sandos-'n-grills-sanjay-nagar,-new-bel-road-sanjay-nagar,-new-bel-road",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "NO. 1, PID No.019-M0021-21, 3rd Floor,KALPANA CHAWLA ROAD, BHOOPASANDRA, HEBBAL, BENGALURU, PIN 560094",
        locality: "Bhoopasandra",
        parentId: 254395,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7194462~p=31~eid=00000188-fcab-e1c5-15fb-f4ac00221f60~srvts=1687866302917",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.9 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "473374",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 2.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "40227",
        name: "Le Arabia",
        uuid: "7d13f8b1-59df-4570-a43c-227e99d417c8",
        city: "1",
        area: "Basaveshwara Nagar",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "s2tcja1qsmkhkxkcly7z",
        cuisines: [
          "Arabian",
          "Beverages",
          "Biryani",
          "Chinese",
          "Desserts",
          "Seafood",
          "Hyderabadi",
          "Ice Cream",
          "Afghani",
          "Grill",
          "Tandoor",
        ],
        tags: [],
        costForTwo: 57000,
        costForTwoString: "₹570 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        slaString: "34 MINS",
        lastMileTravel: 5,
        slugs: {
          restaurant: "le-arabia-basaveshwara-nagar-rajajinagar",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "881/B-1, 2nd Stage, WOC Road, Basaveshwaranagar, Bengaluru, Karnataka 560086",
        locality: "Basaveshwara Nagar",
        parentId: 7457,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 5200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5200,
          message: "",
          title: "Delivery Charge",
          amount: "5200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹80",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "40227",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          lastMileTravel: 5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.7",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "23826",
        name: "Domino's Pizza",
        uuid: "b8589a20-b4a4-45f0-b460-354a26c09217",
        city: "1",
        area: "Yeshwanthpur",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "sg9xutecl14q6qclvwsi",
        cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
        tags: [],
        costForTwo: 40000,
        costForTwoString: "₹400 FOR TWO",
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: "25 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant:
            "dominos-pizza-mathikere-main-road-sanjay-nagar-new-bel-road-yeshwanthpur",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Mathikere Main Road, Bangalore Ground Floor, N0. 25/4, Mathikere Main Road (Next To Sangeetha Mobiles) Mathikere, Bangalore, Karnataka-560054",
        locality: "Gokula 1st Stage",
        parentId: 2456,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹999",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "23826",
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 0,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.4",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "402626",
        name: "Kolkata Famous Kati Roll",
        uuid: "e42b4840-8ca1-4689-9f3c-d3163ae514d9",
        city: "1",
        area: "Yeshwanthpur",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "nkwlpkhss6c4rgblkcak",
        cuisines: ["Snacks", "Beverages"],
        tags: [],
        costForTwo: 9900,
        costForTwoString: "₹99 FOR TWO",
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: "24 MINS",
        lastMileTravel: 3.5999999046325684,
        slugs: {
          restaurant: "kolkata-famous-kati-roll-yeshwanthpur-yeshwanthpur",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Near SBI Bank, Factory Main Road, opposite to Brigade Courtyard, Jalahalli Village, 2nd Stage, Bengaluru, Dasarahalli , B.B.M.P North, Karnataka - 560013",
        locality: "2nd Stage",
        parentId: 3550,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3300,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.5 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "402626",
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 3.5999999046325684,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.5",
        totalRatings: 100,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "653419",
        name: "Easy Bites By Empire",
        uuid: "fc320364-2ba6-4687-b2f0-52019ae0c102",
        city: "1",
        area: "New Bel Road",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "3607a6af73ba20341a09eaf46a111f52",
        cuisines: ["Snacks", "Fast Food", "Beverages"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        slaString: "20 MINS",
        lastMileTravel: 1.100000023841858,
        slugs: {
          restaurant:
            "easy-bites-by-empire-sanjay-nagar,-new-bel-road-sanjay-nagar,-new-bel-road",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "EASY BITES BY EMPIRE, NO.218, SM PLAZA, NEW BEL ROAD, BANGALORE., Yeshwanthapura , B.B.M.P North, Karnataka, 560054",
        locality: "KGE Layout",
        parentId: 8503,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹40",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "653419",
          deliveryTime: 20,
          minDeliveryTime: 20,
          maxDeliveryTime: 20,
          lastMileTravel: 1.100000023841858,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "510627",
        name: "Lulu Hypermarket",
        uuid: "6ed6d642-4b74-42a4-b1c7-ac27d09a80f0",
        city: "1",
        area: "Rajajinagar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "usvu7jwfx9t47z3y3lkh",
        cuisines: ["Arabian", "Continental", "North Indian", "Chinese"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 45,
        minDeliveryTime: 45,
        maxDeliveryTime: 45,
        slaString: "45 MINS",
        lastMileTravel: 7.400000095367432,
        slugs: {
          restaurant:
            "lulu-international-shopping-malls-pvt-ltd-hypermar-majestic-majestic",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "LuLu Hyper market ,No 19/2,Part of CTS No 2, Mysore Deviation Road,Gopalapura (Ward No 96), Bangalore -560023",
        locality: "Mysore Deviation Road",
        parentId: 19980,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 6400,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6400,
          message: "",
          title: "Delivery Charge",
          amount: "6400",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "510627",
          deliveryTime: 45,
          minDeliveryTime: 45,
          maxDeliveryTime: 45,
          lastMileTravel: 7.400000095367432,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "535787",
        name: "Donne Biriyani Mane",
        uuid: "fac8ce3b-a14f-45b4-82fd-edbb0687c25e",
        city: "1",
        area: "Yeshwanthpur",
        totalRatingsString: "50+ ratings",
        cloudinaryImageId: "ur9k5rzweqqbt2ms7wpf",
        cuisines: ["Biryani", "Indian"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        slaString: "22 MINS",
        lastMileTravel: 3,
        slugs: {
          restaurant: "donne-biriyani-mane-yeshwanthpur-yeshwanthpur",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "NO 20, SREE BHAVANI, NEAR CSI CHURCH, JALAHALLI, SHARADAMBA NAGAR, BANGALORE 560013",
        locality: "Sharadamba Nagar",
        parentId: 5628,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3300,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "535787",
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          lastMileTravel: 3,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 50,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "478720",
        name: "Razakhiya Hotel",
        uuid: "e640e559-c24d-49b1-ba84-b2120505359e",
        city: "1",
        area: "Hebbala",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "fwptwtb9qiswckinje1f",
        cuisines: ["North Indian", "Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 48,
        minDeliveryTime: 48,
        maxDeliveryTime: 48,
        slaString: "48 MINS",
        lastMileTravel: 8,
        slugs: {
          restaurant: "razakhiya-hotel-frazer-town-frazer-town",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "No 8/40,9th Main,3rd Stage next to Bilal Masjid Asthana Pillana Garden,Hebbala, bangalore-560045",
        locality: "3rd Stage",
        parentId: 21645,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 6400,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6400,
          message: "",
          title: "Delivery Charge",
          amount: "6400",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹40",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "478720",
          deliveryTime: 48,
          minDeliveryTime: 48,
          maxDeliveryTime: 48,
          lastMileTravel: 8,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "196047",
        name: "New Taj Darbar",
        uuid: "94a6fc19-e819-4450-b52f-a96c5a32d565",
        city: "1",
        area: "Shivajinagar",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "nfieyqgxk1omknxfbluj",
        cuisines: ["Biryani", "Indian", "Chinese", "Tandoor", "Seafood"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 59,
        minDeliveryTime: 59,
        maxDeliveryTime: 59,
        slaString: "59 MINS",
        lastMileTravel: 8.100000381469727,
        slugs: {
          restaurant: "new-taj-darbar-central-bangalore-central-bangalore",
          city: "bangalore",
        },
        cityState: "1",
        address: "New Taj Darbar, Shivaji Nagar, Bengaluru, Karnataka, India",
        locality: "Saint Mary's Church Road",
        parentId: 148190,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 7900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7900,
          message: "",
          title: "Delivery Charge",
          amount: "7900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "8.1 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "30% OFF",
          subHeader: "UPTO ₹75",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "196047",
          deliveryTime: 59,
          minDeliveryTime: 59,
          maxDeliveryTime: 59,
          lastMileTravel: 8.100000381469727,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.4",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "31765",
        name: "Donne Biriyani Angadi Mane",
        uuid: "178dd43f-2bc1-490a-bfb2-b1cf45e6bc1a",
        city: "1",
        area: "Malleshwaram",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "b4b19cfe9911a0e0327d5a9f2ac7490f",
        cuisines: ["Biryani", "South Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: "26 MINS",
        lastMileTravel: 3.9000000953674316,
        slugs: {
          restaurant:
            "donne-biriyani-angadi-mane-malleshwaram-sadashiv-nagar-malleshwaram",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "188/32/1,13cross,Bhasyam circle, sadashivanagar, banglore 560080",
        locality: "Bashyam Circle",
        parentId: 2915,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3300,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3300,
          message: "",
          title: "Delivery Charge",
          amount: "3300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.9 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "31765",
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 3.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.8",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "5902",
        name: "Polar Bear Ice Cream Sundaes",
        uuid: "965710cc-7c4b-438e-880c-71b694b1a318",
        city: "1",
        area: "New Bel Road",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "57262fe3839f0bff174f3d7e7cc8a2b4",
        cuisines: ["Ice Cream", "Beverages", "Desserts"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        slaString: "19 MINS",
        lastMileTravel: 1.399999976158142,
        slugs: {
          restaurant: "polar-bear-sanjay-nagar-new-bel-road-yeshwanthpur",
          city: "bangalore",
        },
        cityState: "1",
        address: "83, 80 Feet Road, RMV 2nd Stage, New BEL Road, Bangalore",
        locality: "2Nd Stage",
        parentId: 726,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "5902",
          deliveryTime: 19,
          minDeliveryTime: 19,
          maxDeliveryTime: 19,
          lastMileTravel: 1.399999976158142,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.4",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "180847",
        name: "Bombay Vadapav Corner",
        uuid: "e3545ed1-c1f3-4926-bcf8-f21933e1bc7a",
        city: "1",
        area: "Malleshwaram",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "lynwmpukcdxjrizoklfa",
        cuisines: ["North Indian"],
        tags: [],
        costForTwo: 10000,
        costForTwoString: "₹100 FOR TWO",
        deliveryTime: 31,
        minDeliveryTime: 31,
        maxDeliveryTime: 31,
        slaString: "31 MINS",
        lastMileTravel: 5.599999904632568,
        slugs: {
          restaurant:
            "bombay-vadapav-corner-seshadripuram1st-main-road-malleshwaram",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "Sri Ganesha Bombay vada Pav corner, #23/1, 1st Main road ,sheshadripuram, Bangalore",
        locality: "Jai Bheema Nagar",
        parentId: 48912,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 5200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 5200,
          message: "",
          title: "Delivery Charge",
          amount: "5200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "180847",
          deliveryTime: 31,
          minDeliveryTime: 31,
          maxDeliveryTime: 31,
          lastMileTravel: 5.599999904632568,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "32738",
        name: "Donne Biryani House",
        uuid: "706ff8df-6c75-4970-8130-3fe7a8c2bbbb",
        city: "1",
        area: "Malleshwaram",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "cgtfmodhd9gme13pblre",
        cuisines: ["Biryani", "South Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: "30 MINS",
        lastMileTravel: 4.699999809265137,
        slugs: {
          restaurant: "donne-biryani-house-malleshwaram-malleshwaram",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "19, 2nd 2cross, MN Complex, Sampige road, Malleshwaram, Bangalore - 560003",
        locality: "Sampige road",
        parentId: 338,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3900,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3900,
          message: "",
          title: "Delivery Charge",
          amount: "3900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.6 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "15% OFF",
          subHeader: "ABOVE ₹600",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        sla: {
          restaurantId: "32738",
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 4.699999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.0",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "1425",
        name: "Rolls Kitchen",
        uuid: "a593aaa5-911a-444c-a899-9a8d9cbd4367",
        city: "1",
        area: "New BEL Road",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "lszgkbuvaiht7orqbc1y",
        cuisines: ["Fast Food"],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 13,
        minDeliveryTime: 13,
        maxDeliveryTime: 13,
        slaString: "13 MINS",
        lastMileTravel: 0.20000000298023224,
        slugs: {
          restaurant:
            "rolls-kitchen-msr-nagar-sanjay-nagar-new-bel-road-yeshwanthpur",
          city: "bangalore",
        },
        cityState: "1",
        address:
          "No 21, 1st Main, Near MS Ramaiah School, MSR Nagar, New BEL Road",
        locality: "MSR Nagar",
        parentId: 781,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "0.2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "1425",
          deliveryTime: 13,
          minDeliveryTime: 13,
          maxDeliveryTime: 13,
          lastMileTravel: 0.20000000298023224,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];

export function getRestaurantDetails(obj: any) {
  const {
    type,
    data: {
      id,
      name,
      uuid,
      cuisines,
      costForTwo,
      costForTwoString,
      deliveryTime,
      address,
      veg,
      favorite,
      avgRating,
      totalRatings,
    },
    subtype,
  } = obj;

  return {
    type,
    id,
    name,
    uuid,
    cuisines,
    costForTwo,
    costForTwoString,
    deliveryTime,
    address,
    veg,
    favorite,
    avgRating,
    totalRatings,
    subtype,
  };
}
